return {
    -- Keybinds (client uses these)
    Keybinds = {
        EquipSaber = Enum.KeyCode.One,
        IgniteSaber = Enum.KeyCode.Q,
    },

    -- Animation IDs (replace with actual R6/R15 anim IDs)
    Animations = {
        Equip = "rbxassetid://0",
        Unequip = "rbxassetid://0",
        IdleHolding = "rbxassetid://0"
    },

    -- Replications
    RemoteNames = {
        EquipRequest = "Saber_EquipRequest",
        IgniteRequest = "Saber_IgniteRequest",
        EquipChanged = "Saber_EquipChanged",
        IgniteChaned = "Saber_IgniteChanged",
    },
}
